name: mlomics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pip:
      - torch
      - tensorflow==2.10.0
      - keras>=2.3.1